# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern: ^/([a-z]{2})/admin/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: admin_main_home
                always_use_default_target_path: true
                use_referer: true
                failure_path: admin_login
            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: admin_main_home
            logout:
                path: admin_logout
                target: /admin
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week in seconds
                path: /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[a-z]/admin/, role: ROLE_ADMIN }