services:
    withdraw.service:
        class: WithdrawBundle\Service\WithdrawService\WithdrawService
        calls:
            - [setContainer, ['@service_container']]

    withdraw.backend.menu:
        class:  WithdrawBundle\DataFixtures\ORM\LoadMenu
        tags:
            - { name: backend.menu.fixture }